// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl-g4D3UWGquu-4HxGnKRcyrA6NNGvZnA',
    appId: '1:707731658517:web:f024dff40ffa2811c87b1c',
    messagingSenderId: '707731658517',
    projectId: 'socializer-ba164',
    authDomain: 'socializer-ba164.firebaseapp.com',
    storageBucket: 'socializer-ba164.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMPEa_1Wflt8WPL7tAYRTzwYOgCOa4UQ',
    appId: '1:707731658517:android:241581f6ada56c69c87b1c',
    messagingSenderId: '707731658517',
    projectId: 'socializer-ba164',
    storageBucket: 'socializer-ba164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ4u8kcuuKDPOB9e1H7cGnn_HAaFDdyLQ',
    appId: '1:707731658517:ios:281d914063aa646ac87b1c',
    messagingSenderId: '707731658517',
    projectId: 'socializer-ba164',
    storageBucket: 'socializer-ba164.firebasestorage.app',
    iosBundleId: 'com.example.socializer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ4u8kcuuKDPOB9e1H7cGnn_HAaFDdyLQ',
    appId: '1:707731658517:ios:281d914063aa646ac87b1c',
    messagingSenderId: '707731658517',
    projectId: 'socializer-ba164',
    storageBucket: 'socializer-ba164.firebasestorage.app',
    iosBundleId: 'com.example.socializer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl-g4D3UWGquu-4HxGnKRcyrA6NNGvZnA',
    appId: '1:707731658517:web:6f65c41427c58160c87b1c',
    messagingSenderId: '707731658517',
    projectId: 'socializer-ba164',
    authDomain: 'socializer-ba164.firebaseapp.com',
    storageBucket: 'socializer-ba164.firebasestorage.app',
  );
}
